FROM --platform=$BUILDPLATFORM docker.io/library/alpine AS alpine-builder
WORKDIR /app

ARG TARGETOS
ARG TARGETARCH

ARG ALPINE_REPO_URL=https://dl-cdn.alpinelinux.org/alpine \
    ALPINE_REPO_VERSION=edge \
    GIT_REPOSITORY=https://github.com/fatedier/frp.git \
    GIT_BRANCH=v0.58.0 \
    CGO_ENABLED=0 \
    GOPATH=/app/go

RUN apk upgrade --no-cache \
    && apk add --no-cache --virtual build-deps --repository=${ALPINE_REPO_URL}/${ALPINE_REPO_VERSION}/main \
        jq \
        git \
        tar \
        bash \
        curl \
        file \
    && export GO_VERSION=$(curl https://go.dev/dl/?mode=json | jq -r '.[0].version' ) \
    && curl -LO go.dev/dl/"${GO_VERSION}".linux-amd64.tar.gz \
    && tar -C /usr/local -xzf "${GO_VERSION}".linux-amd64.tar.gz \
    && rm "${GO_VERSION}".linux-amd64.tar.gz \
    && export PATH="${PATH}":/usr/local/go/bin:/app/go/bin \
    && mkdir -p "${GOPATH}" \
    && cd "${GOPATH}" \
    && git config --global --add safe.directory '*' \
    && git clone --branch "${GIT_BRANCH}" "${GIT_REPOSITORY}" \
    && cd frp \
    && git init \
    && GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" go build -o /app/go/bin/frps-"${TARGETARCH}" -a -trimpath -ldflags '-w -s' ./cmd/frps \
    && GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" go build -o /app/go/bin/frpc-"${TARGETARCH}" -a -trimpath -ldflags '-w -s' ./cmd/frpc \
    && file /app/go/bin/frps-"${TARGETARCH}" \
    && file /app/go/bin/frpc-"${TARGETARCH}" \
    && apk del --rdepends \
        build-deps \
    && rm -rf /app/go/cache /tmp /usr/local/go /app/go/frp
